#!/bin/bash
#SBATCH --job-name="IQout"
#SBATCH --time=24:00:00  # walltime limit (HH:MM:SS)
#SBATCH --nodes=1   # number of nodes
#SBATCH --ntasks-per-node=1   # processor core(s) per node
#SBATCH -c 1
#SBATCH --mem-per-cpu=8G
#SBATCH --mail-user="biancani@uri.edu" #CHANGE THIS to your user email address
#SBATCH --mail-type=ALL

## UPDATE PATHS as necessary

# path to project directory:
PROJECT=/data/schwartzlab/Biancani/PlacentalPolytomy
# path to output folder for IQ-TREE
OUTPUT=$PROJECT/output/02_iqtree_assessment
# path to array files (array_list.txt and aligned_loci_list_* created by 02.00_iqtree_prep.sh)
ARRAY=$OUTPUT/02.00_array_prep_files
# paths to output directories created by 02.00_iqtree_prep.sh:
CombineOUT=$OUTPUT/02.01_compare_hypotheses
# path to likelihood outputs (generated by 02.01_iqtree_array.sh):
LnL=$OUTPUT/02.01_compare_hypotheses/likelihood
# path to sCF outputs (generated by 02.01_iqtree_array.sh):
sCF=$OUTPUT/02.01_compare_hypotheses/scf

output_prefix="combined"

date
cd $CombineOUT

# concatenate likelihood output files
cat ${LnL}/LnLs_*.csv > ${output_prefix}_dLnLs.csv

# initialize empty combined sCF file
> ${output_prefix}_scf.csv
# iterate trhough list of locus names:
cat ${ARRAY}/array_list.txt | while read array_list_line
do
  # read scf output for each locus
  cat ${ARRAY}/${array_list_line} | while read aligned_loci_list_line
  do
    # construct the full path to the corresponding sCF output file for the locus
    fscf="${sCF}/scf_${aligned_loci_list_line}"
    # extract the sCF values (second column) for each hypothesis (lines 2, 3, and 4)
    # and write full file path and 3 sCF values as a new line in the combined CSV
    echo $fscf","$(sed -n 2p $fscf | cut -f2 -d,)","$(sed -n 3p $fscf | cut -f2 -d,)","$(sed -n 4p $fscf | cut -f2 -d,) >> ${output_prefix}_scf.csv
  done
done
# remove path and prefix from the first field leaving only the locus name: 
sed -i -e "s+${sCF}/scf_++g" ${output_prefix}_scf.csv
date